# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
