# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-19 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='desc',
        ),
    ]
